services:
  pruebatecsupermercado:
    build: PruebaTecSupermercado
    mem_limit: 512m
    ports:
      - "${APP_PORT}:8080"
    environment:
      - DB_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USER_NAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PLATFORM=${DB_PLATFORM}
    restart: always